# AUTOGENERATED FROM 'letta_bot/queries/check_pending_request.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import enum
import gel


class ResourceType(enum.Enum):
    ACCESS_IDENTITY = "access_identity"
    CREATE_AGENT_FROM_TEMPLATE = "create_agent_from_template"
    ACCESS_AGENT = "access_agent"


async def check_pending_request(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
    resource_type: ResourceType,
) -> bool:
    return await executor.query_single(
        """\
        select exists (
            select AuthorizationRequest
            filter
                .user.telegram_id = <int64>$telegram_id
                and .resource_type = <ResourceType>$resource_type
                and .status = AuthStatus.pending
        )\
        """,
        telegram_id=telegram_id,
        resource_type=resource_type,
    )
