# AUTOGENERATED FROM 'letta_bot/queries/check_pending_agent_access_request.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import enum
import gel


class AuthStatus(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


class ResourceType(enum.Enum):
    ACCESS_IDENTITY = "access_identity"
    CREATE_AGENT_FROM_TEMPLATE = "create_agent_from_template"
    ACCESS_AGENT = "access_agent"


async def check_pending_agent_access_request(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
    resource_type: ResourceType,
    agent_id: str,
    status: AuthStatus,
) -> bool:
    return await executor.query_single(
        """\
        # Check if user already has a pending agent access request for a specific agent
        select exists (
            select AuthorizationRequest
            filter
                .user.telegram_id = <int64>$telegram_id
                and .resource_type = <ResourceType>$resource_type
                and .resource_id = <str>$agent_id
                and .status = <AuthStatus>$status
        )\
        """,
        telegram_id=telegram_id,
        resource_type=resource_type,
        agent_id=agent_id,
        status=status,
    )
