# AUTOGENERATED FROM 'letta_bot/queries/create_identity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateIdentityResult(NoPydanticValidation):
    id: uuid.UUID


async def create_identity(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
    identifier_key: str,
    identity_id: str,
) -> CreateIdentityResult:
    return await executor.query_single(
        """\
        insert Identity {
            user := (select User filter .telegram_id = <int64>$telegram_id),
            identifier_key := <str>$identifier_key,
            identity_id := <str>$identity_id
        };\
        """,
        telegram_id=telegram_id,
        identifier_key=identifier_key,
        identity_id=identity_id,
    )
