# AUTOGENERATED FROM 'letta_bot/queries/create_auth_request.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateAuthRequestResult(NoPydanticValidation):
    id: uuid.UUID


class ResourceType(enum.Enum):
    ACCESS_IDENTITY = "access_identity"
    CREATE_AGENT_FROM_TEMPLATE = "create_agent_from_template"
    ACCESS_AGENT = "access_agent"


async def create_auth_request(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
    resource_type: ResourceType,
    resource_id: str,
) -> CreateAuthRequestResult:
    return await executor.query_single(
        """\
        insert AuthorizationRequest {
            user := (select User filter .telegram_id = <int64>$telegram_id),

            resource_type := <ResourceType>$resource_type,
            resource_id := <str>$resource_id,

            # default status is pending
            # maybe include message in the future
        };\
        """,
        telegram_id=telegram_id,
        resource_type=resource_type,
        resource_id=resource_id,
    )
