# AUTOGENERATED FROM 'letta_bot/queries/get_auth_request_by_id.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class AuthStatus(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


@dataclasses.dataclass
class GetAuthRequestByIdResult(NoPydanticValidation):
    id: uuid.UUID
    user: GetAuthRequestByIdResultUser
    resource_id: str
    resource_type: ResourceType
    status: AuthStatus
    message: str | None
    created_at: datetime.datetime


@dataclasses.dataclass
class GetAuthRequestByIdResultUser(NoPydanticValidation):
    id: uuid.UUID
    telegram_id: int
    username: str | None
    first_name: str
    last_name: str | None
    full_name: str | None


class ResourceType(enum.Enum):
    ACCESS_IDENTITY = "access_identity"
    CREATE_AGENT_FROM_TEMPLATE = "create_agent_from_template"
    ACCESS_AGENT = "access_agent"


async def get_auth_request_by_id(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetAuthRequestByIdResult | None:
    return await executor.query_single(
        """\
        # Get authorization request by ID without modifying it
        select AuthorizationRequest {
            id,
            user: {
                telegram_id,
                username,
                first_name,
                last_name,
                full_name
            },
            resource_id,
            resource_type,
            status,
            message,
            created_at
        }
        filter .id = <uuid>$id;\
        """,
        id=id,
    )
