# AUTOGENERATED FROM 'letta_bot/queries/get_user_by_telegram_id.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByTelegramIdResult(NoPydanticValidation):
    id: uuid.UUID
    telegram_id: int
    username: str | None
    first_name: str
    last_name: str | None
    full_name: str | None


async def get_user_by_telegram_id(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
) -> GetUserByTelegramIdResult | None:
    return await executor.query_single(
        """\
        # Get user by telegram_id
        select User {
            telegram_id,
            username,
            first_name,
            last_name,
            full_name
        }
        filter .telegram_id = <int64>$telegram_id;\
        """,
        telegram_id=telegram_id,
    )
