# AUTOGENERATED FROM 'letta_bot/queries/get_identity_request_status.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class AuthStatus(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


@dataclasses.dataclass
class GetIdentityRequestStatusResult(NoPydanticValidation):
    id: uuid.UUID
    status: AuthStatus


async def get_identity_request_status(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
) -> GetIdentityRequestStatusResult | None:
    return await executor.query_single(
        """\
        # Returns identity request if pending or allowed (null if none or denied/revoked)
        select AuthorizationRequest { id, status }
        filter .user.telegram_id = <int64>$telegram_id
            and .resource_type = ResourceType.access_identity
            and .status in {AuthStatus.pending, AuthStatus.allowed}
        limit 1;\
        """,
        telegram_id=telegram_id,
    )
