# AUTOGENERATED FROM 'letta_bot/queries/get_allowed_identity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetAllowedIdentityResult(NoPydanticValidation):
    id: uuid.UUID


async def get_allowed_identity(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
) -> list[GetAllowedIdentityResult]:
    return await executor.query(
        """\
        select AuthorizationRequest { id } 
        filter .user.telegram_id = <int64>$telegram_id
            and .status = AuthStatus.allowed and .resource_type = ResourceType.access_identity;\
        """,
        telegram_id=telegram_id,
    )
