# AUTOGENERATED FROM 'letta_bot/queries/get_pending_requests_by_agent.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetPendingRequestsByAgentResult(NoPydanticValidation):
    id: uuid.UUID
    user: GetPendingRequestsByAgentResultUser
    resource_id: str


@dataclasses.dataclass
class GetPendingRequestsByAgentResultUser(NoPydanticValidation):
    id: uuid.UUID
    telegram_id: int
    first_name: str
    full_name: str | None
    username: str | None


async def get_pending_requests_by_agent(
    executor: gel.AsyncIOExecutor,
    *,
    agent_id: str,
) -> list[GetPendingRequestsByAgentResult]:
    return await executor.query(
        """\
        select AuthorizationRequest {
            id,
            user: { telegram_id, first_name, full_name, username },
            resource_id,
        }
        filter
            .resource_type = ResourceType.access_agent
            and .resource_id = <str>$agent_id
            and .status = AuthStatus.pending\
        """,
        agent_id=agent_id,
    )
