# AUTOGENERATED FROM 'letta_bot/queries/get_identity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetIdentityResult(NoPydanticValidation):
    id: uuid.UUID
    user: GetIdentityResultUser
    identifier_key: str
    selected_agent: str | None
    created_at: datetime.datetime


@dataclasses.dataclass
class GetIdentityResultUser(NoPydanticValidation):
    id: uuid.UUID
    username: str | None
    telegram_id: int
    first_name: str
    last_name: str | None
    full_name: str | None
    is_bot: bool
    language_code: str | None
    first_seen: datetime.datetime


async def get_identity(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
) -> list[GetIdentityResult]:
    return await executor.query(
        """\
        select Identity {
            user: {*},
            identifier_key,
            selected_agent,
            created_at,
        }
        filter .user.telegram_id = <int64>$telegram_id;\
        """,
        telegram_id=telegram_id,
    )
