# AUTOGENERATED FROM 'letta_bot/queries/list_auth_requests_by_status.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class AuthStatus(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


class AuthStatus02(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


@dataclasses.dataclass
class ListAuthRequestsByStatusResult(NoPydanticValidation):
    id: uuid.UUID
    status: AuthStatus
    message: str | None
    resource_id: str
    resource_type: ResourceType
    response: str | None
    created_at: datetime.datetime
    updated_by: int | None
    user: ListAuthRequestsByStatusResultUser


@dataclasses.dataclass
class ListAuthRequestsByStatusResultUser(NoPydanticValidation):
    id: uuid.UUID
    username: str | None
    telegram_id: int
    first_name: str
    last_name: str | None
    full_name: str | None
    is_bot: bool
    language_code: str | None
    first_seen: datetime.datetime


class ResourceType(enum.Enum):
    ACCESS_IDENTITY = "access_identity"
    CREATE_AGENT_FROM_TEMPLATE = "create_agent_from_template"
    ACCESS_AGENT = "access_agent"


async def list_auth_requests_by_status(
    executor: gel.AsyncIOExecutor,
    *,
    status: AuthStatus02 | None = None,
) -> list[ListAuthRequestsByStatusResult]:
    return await executor.query(
        """\
        select AuthorizationRequest {**}
        filter .status = <optional AuthStatus>$status ?? .status
        order by .user.telegram_id then .created_at;\
        """,
        status=status,
    )
