# AUTOGENERATED FROM 'letta_bot/queries/register_user.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class RegisterUserResult(NoPydanticValidation):
    id: uuid.UUID
    telegram_id: int


async def register_user(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
    is_bot: bool,
    first_name: str,
    last_name: str | None = None,
    username: str | None = None,
    language_code: str | None = None,
) -> RegisterUserResult:
    return await executor.query_single(
        """\
        select (insert User {
            telegram_id := <int64>$telegram_id,
            is_bot := <bool>$is_bot,
            first_name := <str>$first_name,
            last_name := <optional str>$last_name ?? '',
            username := <optional str>$username ?? '',
            language_code := <optional str>$language_code ?? ''
        }) {telegram_id};\
        """,
        telegram_id=telegram_id,
        is_bot=is_bot,
        first_name=first_name,
        last_name=last_name,
        username=username,
        language_code=language_code,
    )
