# AUTOGENERATED FROM 'letta_bot/queries/resolve_auth_request.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class AuthStatus(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


@dataclasses.dataclass
class ResolveAuthRequestResult(NoPydanticValidation):
    id: uuid.UUID
    user: ResolveAuthRequestResultUser
    resource_type: ResourceType
    resource_id: str


@dataclasses.dataclass
class ResolveAuthRequestResultUser(NoPydanticValidation):
    id: uuid.UUID
    username: str | None
    telegram_id: int
    first_name: str
    last_name: str | None
    full_name: str | None
    first_seen: datetime.datetime
    is_bot: bool
    language_code: str | None


class ResourceType(enum.Enum):
    ACCESS_IDENTITY = "access_identity"
    CREATE_AGENT_FROM_TEMPLATE = "create_agent_from_template"
    ACCESS_AGENT = "access_agent"


async def resolve_auth_request(
    executor: gel.AsyncIOExecutor,
    *,
    auth_status: AuthStatus,
    id: uuid.UUID,
) -> ResolveAuthRequestResult | None:
    return await executor.query_single(
        """\
        select(update AuthorizationRequest
            filter .id = <uuid>$id
            set { status := <AuthStatus>$auth_status }
        ) {user: {*}, resource_type, resource_id};\
        """,
        auth_status=auth_status,
        id=id,
    )
