# AUTOGENERATED FROM 'letta_bot/queries/revoke_user_access.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class RevokeUserAccessResult(NoPydanticValidation):
    id: uuid.UUID


async def revoke_user_access(
    executor: gel.AsyncIOExecutor,
    *,
    telegram_id: int,
) -> list[RevokeUserAccessResult]:
    return await executor.query(
        """\
        update AuthorizationRequest
        filter .user.telegram_id = <int64>$telegram_id and .resource_type = ResourceType.access_identity
        set { status := AuthStatus.revoked };
        # TODO: return identity for information and notification\
        """,
        telegram_id=telegram_id,
    )
