# AUTOGENERATED FROM 'letta_bot/queries/revoke_agent_access.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class AuthStatus(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


class ResourceType(enum.Enum):
    ACCESS_IDENTITY = "access_identity"
    CREATE_AGENT_FROM_TEMPLATE = "create_agent_from_template"
    ACCESS_AGENT = "access_agent"


@dataclasses.dataclass
class RevokeAgentAccessResult(NoPydanticValidation):
    id: uuid.UUID


async def revoke_agent_access(
    executor: gel.AsyncIOExecutor,
    *,
    new_status: AuthStatus,
    telegram_id: int,
    resource_type: ResourceType,
    agent_id: str,
    current_status: AuthStatus,
) -> list[RevokeAgentAccessResult]:
    return await executor.query(
        """\
        # Revoke agent access authorization request
        # Used when admin detaches agent from user's identity
        update AuthorizationRequest
        filter
            .user.telegram_id = <int64>$telegram_id
            and .resource_type = <ResourceType>$resource_type
            and .resource_id = <str>$agent_id
            and .status = <AuthStatus>$current_status
        set {
            status := <AuthStatus>$new_status
        }\
        """,
        new_status=new_status,
        telegram_id=telegram_id,
        resource_type=resource_type,
        agent_id=agent_id,
        current_status=current_status,
    )
