# AUTOGENERATED FROM 'letta_bot/queries/set_selected_agent.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class SetSelectedAgentResult(NoPydanticValidation):
    id: uuid.UUID


async def set_selected_agent(
    executor: gel.AsyncIOExecutor,
    *,
    agent_id: str,
    telegram_id: int,
) -> SetSelectedAgentResult | None:
    return await executor.query_single(
        """\
        update Identity
        filter .user.telegram_id = <int64>$telegram_id
        set { selected_agent := <str>$agent_id };\
        """,
        agent_id=agent_id,
        telegram_id=telegram_id,
    )
