# AUTOGENERATED FROM 'letta_bot/queries/update_auth_request_status.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class AuthStatus(enum.Enum):
    PENDING = "pending"
    ALLOWED = "allowed"
    DENIED = "denied"
    REVOKED = "revoked"


@dataclasses.dataclass
class UpdateAuthRequestStatusResult(NoPydanticValidation):
    id: uuid.UUID


async def update_auth_request_status(
    executor: gel.AsyncIOExecutor,
    *,
    auth_status: AuthStatus,
    id: uuid.UUID,
) -> UpdateAuthRequestStatusResult | None:
    return await executor.query_single(
        """\
        # Update authorization request status
        update AuthorizationRequest
        filter .id = <uuid>$id
        set {
            status := <AuthStatus>$auth_status
        };\
        """,
        auth_status=auth_status,
        id=id,
    )
