telegram-bot-token: ENC[AES256_GCM,data:yPDKzXIQKm/Ohb95mLIMDz9IPV6iuf5zv4jwb7NG4Jcg2G+lAB6RaXOpXeTvyg==,iv:TDoqAOnY9NWF7P0v8CHMIMgThEdNl05rOJkdOX0xNj8=,tag:r0a4SEOEvIpj4li2DM5dSg==,type:str]
letta-project-id: ENC[AES256_GCM,data:viwTEgWcPIIdEwfhqkrOSmm5dIHTsJzKnzBddRbyKxWjTjFA,iv:GKEoAlx1uWVpjCaWPsANEB11YtdxwS5qt2yWVvgpRdk=,tag:yQU5wsbpYFgR/a/xo3jX5w==,type:str]
letta-api-key: ENC[AES256_GCM,data:IOyT7a05Qu2DsIIaFW2MjDDUxK23zDKq3M3RZrQPs+J5X8sycjerWDzbViPvst1QZuBSw4TKV8p/ESWRT8l/0np+ck2L/jRflbwY/JCaWIABm93VUi+KB8vxr7vU4DWkViABkzB3h6C6PRU=,iv:IzfkX8xFQqJUTngCUlgKIhhwZMyWwGfTvRMrChEEVJg=,tag:oY91Nd0jHdc79KQ03foYvQ==,type:str]
gel-password: ENC[AES256_GCM,data:wd5CmS7l5HomMtIJTVopWZwKrkMHgasLxcRgEyYw2ds9/+lhivTBn3z587I=,iv:pLrgxP9BEO4R0ycFQcCmuM12N7Q+Txmbqz7O3u1E6rg=,tag:3KGvuaJ/nyJPOGGMZeV9wQ==,type:str]
openai-api-key: ENC[AES256_GCM,data:IjJxZ6em127411Bs+OBPajBYMz9sB9ZWBiUGFwquDnkgUfDiw1g2VEcrboPk4tKgyb/Vmu5lzgCyEqLOstQp0Q/ajiFXy5wiItiq9Dcq9sKN8lAUIzP+zCU+8QcczUStgE6+0dpZ5Ggr3GmgEIDJjXNYNTwgXiruUr9bugUf+FQIWIDBS7ZmE61M32tJD490HV9KmV46Rt/Jo79Bl0pteIm1qcM=,iv:uSCy1zM/bb3dfCtUYFA44t5azIRMyi5OlyxLWbnZUpI=,tag:HauQ6LjGuaHx5Ym3LdKEAw==,type:str]
traefik-htpasswd: ENC[AES256_GCM,data:+TgHcI1tjyPnPriUr9PiSddKtXqNE/+l9XqDAq5o3sT8hbV0Bgy5i/sNHT/RU4sfjmBwhWH/GWscI78P2NBxScqq,iv:5GTJ8R+oLGCvJ5yifc9NkkIoOk1dQWdILjlM8Z/brkU=,tag:pa6EwXgcVzxq1dwRTIZy3Q==,type:str]
sops:
    age:
        - recipient: age1s9mzrygmeknj349442glp4hngrfag80kc40fcvj55ulkce9659cqygpj27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMWZWUjkrVUwrb2s0R0lN
            cjJXdjRKZ2Z4NVpiOTczVHdCakl6cSt6YmxFCmNENlorZzFXSEdERG0xNGFzbnNZ
            MXdHVVBYLzVGQUp0dFpHV2p1bWNxd1UKLS0tIG1PZ29URVJjYSt5OEhydktsOVBF
            Zi9oUDd1aXQvZmdzcVlwRzVNWUZ2U2cK59eiNTd6sOo0WipD2d9AwDgcAVI+9ewM
            69eaIP8Y0fZ0aqCRtXOFEA9Q8lX1EQuFD4eSq+GU4ITe7dgOA4Ddkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v806dtrmz5glgsywmu8zcdrkdqw4na4js3q2xct9wvczxh88gq9sxpx4rs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYkdzZUk3VTlkeDZBTDF3
            ZUduZkdUUzErRHdvSXZwd2pvcU1BbHN0aGlNCi9qSzU0T3dsZHVmTE9zQ3I5MkVa
            Sm1vbUhVNVpMYzhLbHlKYUFhQ2JjbWsKLS0tIGhLdlEvMGNzSXV2blR0OE1VS0ZB
            Q3M0akliYVVxaGpLYXcrUFBvaDB3dGcK+HBuzucANxjFYFe7wuqKDSQSfNwJ7VvY
            Do+UBo0FSdtjEaB3HckcZK2sdzfK5tZTVJK+x+j4kQeTLSzCUQpYfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T02:54:20Z"
    mac: ENC[AES256_GCM,data:Ua+Yo5Iu+hZCM30KEZGs4il4u0b0ClvYFNhdnoBFgGunjOR4zSG+Ab60HmJ3YLRi6iJH48P1sdt09ci/6ibiCn5kkXUYOX377m5h2CzZ2J0uYeSF6qg391aEReSfPa+i6Z3fdbVucdOLqy3iangP20Kx2encIfSA0o+0yvtW698=,iv:O7mNMUWGfa4Ccno6EBtgsChtuEKBAKKIWvOcqpOk3v8=,tag:P0K1E8QZxmArr6EbVBJAgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
